#dist: trusty
sudo: false
language: java
services: docker
addons:
  hosts:
    - mariadb.example.com

before_install:
  - chmod +x .travis/script.sh
  - chmod +x .travis/build/build.sh
  - chmod +x .travis/build/docker-entrypoint.sh
  - chmod 777 .travis/build/
  - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc

install:
  - mkdir tmp
  - .travis/gen-ssl.sh mariadb.example.com tmp
  - export PACKET=8M

cache:
  directories:
    - $HOME/.m2

matrix:
  allow_failures:
    - env: DB=build:10.6
      jdk: openjdk11
  include:
    - env: DB=build:10.6
      jdk: openjdk11
    - env: SKYSQL=true
      jdk: openjdk11
    - env: SKYSQL_HA=true MAXSCALE_TEST_DISABLE=true
      jdk: openjdk11
    - env: DB=mysql:5.7
      jdk: openjdk11
    - env: DB=mysql:8.0 ADDITIONAL_CONF=--default-authentication-plugin=mysql_native_password --caching_sha2_password_private_key_path=/etc/sslcert/server.key --caching_sha2_password_public_key_path=/etc/sslcert/public.key
      jdk: openjdk11
    - env: DB=mariadb:10.2
      jdk: openjdk11
    - env: DB=mariadb:10.3
      jdk: openjdk11
    - env: DB=mariadb:10.4
      jdk: openjdk11
    - env: DB=mariadb:10.5
      jdk: openjdk11
    - env: DB=mariadb:10.5
      jdk: oraclejdk11
    - env: DB=mariadb:10.5 BENCH=true
      jdk: oraclejdk11
    - env: DB=mariadb:10.5 COMPRESSION=true
      jdk: oraclejdk11
    - env: DB=mariadb:10.5 PACKET=20M
      jdk: openjdk11
    - env: DB=mariadb:10.5 PACKET=40M
      jdk: openjdk11
    - env: DB=mariadb:10.5
      jdk: openjdk12
    - env: DB=mariadb:10.5 MAXSCALE_VERSION=2.5.3 MAXSCALE_TEST_DISABLE=true SSLPORT=4009
      jdk: openjdk11

script:
  - if [[ "$DB" == build* ]] ; then .travis/build/build.sh; fi
  - if [[ "$DB" == build* ]] ; then docker build -t build:10.6 --label build .travis/build/; fi
  - .travis/script.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)