version: '{build}'
environment:
  matrix:
    - DB: '10.2.34'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
      JAVA_HOME: C:\Program Files\Java\jdk11

    - DB: '10.3.25'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
      JAVA_HOME: C:\Program Files\Java\jdk11

    - DB: '10.4.15'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
      JAVA_HOME: C:\Program Files\Java\jdk11

    - DB: '10.5.6'
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_PARAM: 'Visual Studio 15 2017 Win64'
      JAVA_HOME: C:\Program Files\Java\jdk11

clone_folder: c:\projects\mariadb-connector-j
install:
  - cmd: choco install maven
  - cmd: appveyor-download.bat
  - cmd: msiexec /i server.msi INSTALLDIR=c:\projects\server SERVICENAME=mariadb ALLOWREMOTEROOTACCESS=true /qn
  - cmd: "\"c:\\projects\\server\\bin\\mysql.exe\" -e \"create database testj\" --user=root"
  - cmd: SET MAVEN_OPTS=-Xms512m -Xms768m
  - cmd: SET JAVA_OPTS=-Xms512m -Xmx768m
  - cmd: cd c:\projects\mariadb-connector-j
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean
  - mvn test -Dmaven.test.skip=true
test_script:
  - mvn test -DdbUrl="jdbc:mariadb://localhost/testj?user=root"
